@startuml

class カホンコントローラ
class ファイルマネージャー
{
  +楽譜リスト
  +HTMLファイル
  +SDカード接続状態
  楽譜リスト取得()
  HTMLファイル取得()
}
class 音楽再生管理
{
  +楽譜情報
  +楽譜進行度
  楽譜情報登録()
  楽譜再生開始()
  楽譜一時停止()
}
class ソレノイド駆動
{

}
class HTTPサーバー
{
}
class SDカード
{
  OPEN()
  CLOSE()
  READ()
  WRITE()
}
class Wifi
class LED
class 再生ボタン
class 停止ボタン
class FET


カホンコントローラ ..> ファイルマネージャー
カホンコントローラ ..> 音楽再生管理
カホンコントローラ ..> 再生ボタン
カホンコントローラ ..> 停止ボタン
カホンコントローラ ..> HTTPサーバー
ファイルマネージャー ..> SDカード
音楽再生管理 ..> ソレノイド駆動
ソレノイド駆動 ..> FET
HTTPサーバー ..> Wifi
HTTPサーバー ..> ファイルマネージャー
HTTPサーバー ..> 音楽再生管理

@enduml
